-- ════════════════════════════════════════════════════════════════════
-- gazetteer_seed_lgas
--
-- All 774 Nigerian Local Government Areas.
--
-- Source   : https://github.com/xosasx/nigerian-local-government-areas (lgas.json)
-- Licence  : MIT
-- Retrieved: 2026-08-28
-- Provenance: each source record carries a Wikidata identifier.
--
-- Verified at generation time: 774 records, 37 distinct ISO 3166-2:NG state
-- codes matching public.ng_states exactly (no missing, no extra), no duplicate
-- (state, name) pairs, no slug collisions. Per-state spot checks against the
-- published figures: FCT 6, Lagos 20, Kano 44.
--
-- code = <ISO state code>-<slugified LGA name>, e.g. LA-ikeja.
-- ════════════════════════════════════════════════════════════════════

insert into public.ng_lgas (code, state_code, name) values
  ('AB-aba-north','AB','Aba North'),
  ('AB-aba-south','AB','Aba South'),
  ('AB-arochukwu','AB','Arochukwu'),
  ('AB-bende','AB','Bende'),
  ('AB-ikwuano','AB','Ikwuano'),
  ('AB-isiala-ngwa-north','AB','Isiala Ngwa North'),
  ('AB-isiala-ngwa-south','AB','Isiala Ngwa South'),
  ('AB-isuikwuato','AB','Isuikwuato'),
  ('AB-obi-ngwa','AB','Obi Ngwa'),
  ('AB-ohafia','AB','Ohafia'),
  ('AB-osisioma','AB','Osisioma'),
  ('AB-ugwunagbo','AB','Ugwunagbo'),
  ('AB-ukwa-east','AB','Ukwa East'),
  ('AB-ukwa-west','AB','Ukwa West'),
  ('AB-umu-nneochi','AB','Umu-Nneochi'),
  ('AB-umuahia-north','AB','Umuahia North'),
  ('AB-umuahia-south','AB','Umuahia South'),
  ('AD-demsa','AD','Demsa'),
  ('AD-fufore','AD','Fufore'),
  ('AD-ganye','AD','Ganye'),
  ('AD-girei','AD','Girei'),
  ('AD-gombi','AD','Gombi'),
  ('AD-guyuk','AD','Guyuk'),
  ('AD-hong','AD','Hong'),
  ('AD-jada','AD','Jada'),
  ('AD-lamurde','AD','Lamurde'),
  ('AD-madagali','AD','Madagali'),
  ('AD-maiha','AD','Maiha'),
  ('AD-mayo-belwa','AD','Mayo Belwa'),
  ('AD-michika','AD','Michika'),
  ('AD-mubi-north','AD','Mubi North'),
  ('AD-mubi-south','AD','Mubi South'),
  ('AD-numan','AD','Numan'),
  ('AD-shelleng','AD','Shelleng'),
  ('AD-song','AD','Song'),
  ('AD-toungo','AD','Toungo'),
  ('AD-yola-north','AD','Yola North'),
  ('AD-yola-south','AD','Yola South'),
  ('AK-abak','AK','Abak'),
  ('AK-eastern-obolo','AK','Eastern Obolo'),
  ('AK-eket','AK','Eket'),
  ('AK-esit-eket','AK','Esit Eket'),
  ('AK-essien-udim','AK','Essien Udim'),
  ('AK-etim-ekpo','AK','Etim Ekpo'),
  ('AK-etinan','AK','Etinan'),
  ('AK-ibeno','AK','Ibeno'),
  ('AK-ibesikpo-asutan','AK','Ibesikpo Asutan'),
  ('AK-ibiono-ibom','AK','Ibiono Ibom'),
  ('AK-ika','AK','Ika'),
  ('AK-ikono','AK','Ikono'),
  ('AK-ikot-abasi','AK','Ikot Abasi'),
  ('AK-ikot-ekpene','AK','Ikot Ekpene'),
  ('AK-ini','AK','Ini'),
  ('AK-itu','AK','Itu'),
  ('AK-mbo','AK','Mbo'),
  ('AK-mkpat-enin','AK','Mkpat Enin'),
  ('AK-nsit-atai','AK','Nsit Atai'),
  ('AK-nsit-ibom','AK','Nsit Ibom'),
  ('AK-nsit-ubium','AK','Nsit Ubium'),
  ('AK-obot-akara','AK','Obot Akara'),
  ('AK-okobo','AK','Okobo'),
  ('AK-onna','AK','Onna'),
  ('AK-oron','AK','Oron'),
  ('AK-oruk-anam','AK','Oruk Anam'),
  ('AK-udung-uko','AK','Udung Uko'),
  ('AK-ukanafun','AK','Ukanafun'),
  ('AK-uruan','AK','Uruan'),
  ('AK-urue-offong-oruko','AK','Urue Offong/Oruko'),
  ('AK-uyo','AK','Uyo'),
  ('AN-aguata','AN','Aguata'),
  ('AN-anambra-east','AN','Anambra East'),
  ('AN-anambra-west','AN','Anambra West'),
  ('AN-anaocha','AN','Anaocha'),
  ('AN-awka-north','AN','Awka North'),
  ('AN-awka-south','AN','Awka South'),
  ('AN-ayamelum','AN','Ayamelum'),
  ('AN-dunukofia','AN','Dunukofia'),
  ('AN-ekwusigo','AN','Ekwusigo'),
  ('AN-idemili-north','AN','Idemili North'),
  ('AN-idemili-south','AN','Idemili South'),
  ('AN-ihiala','AN','Ihiala'),
  ('AN-njikoka','AN','Njikoka'),
  ('AN-nnewi-north','AN','Nnewi North'),
  ('AN-nnewi-south','AN','Nnewi South'),
  ('AN-ogbaru','AN','Ogbaru'),
  ('AN-onitsha-north','AN','Onitsha North'),
  ('AN-onitsha-south','AN','Onitsha South'),
  ('AN-orumba-north','AN','Orumba North'),
  ('AN-orumba-south','AN','Orumba South'),
  ('AN-oyi','AN','Oyi'),
  ('BA-alkaleri','BA','Alkaleri'),
  ('BA-bauchi','BA','Bauchi'),
  ('BA-bogoro','BA','Bogoro'),
  ('BA-damban','BA','Damban'),
  ('BA-darazo','BA','Darazo'),
  ('BA-dass','BA','Dass'),
  ('BA-gamawa','BA','Gamawa'),
  ('BA-ganjuwa','BA','Ganjuwa'),
  ('BA-giade','BA','Giade'),
  ('BA-itas-gadau','BA','Itas/Gadau'),
  ('BA-jama-are','BA','Jama''are'),
  ('BA-katagum','BA','Katagum'),
  ('BA-kirfi','BA','Kirfi'),
  ('BA-misau','BA','Misau'),
  ('BA-ningi','BA','Ningi'),
  ('BA-shira','BA','Shira'),
  ('BA-tafawa-balewa','BA','Tafawa Balewa'),
  ('BA-toro','BA','Toro'),
  ('BA-warji','BA','Warji'),
  ('BA-zaki','BA','Zaki'),
  ('BE-ado','BE','Ado'),
  ('BE-agatu','BE','Agatu'),
  ('BE-apa','BE','Apa'),
  ('BE-buruku','BE','Buruku'),
  ('BE-gboko','BE','Gboko'),
  ('BE-guma','BE','Guma'),
  ('BE-gwer-east','BE','Gwer East'),
  ('BE-gwer-west','BE','Gwer West'),
  ('BE-katsina-ala','BE','Katsina Ala'),
  ('BE-konshisha','BE','Konshisha'),
  ('BE-kwande','BE','Kwande'),
  ('BE-logo','BE','Logo'),
  ('BE-makurdi','BE','Makurdi'),
  ('BE-obi','BE','Obi'),
  ('BE-ogbadibo','BE','Ogbadibo'),
  ('BE-ohimini','BE','Ohimini'),
  ('BE-oju','BE','Oju'),
  ('BE-okpokwu','BE','Okpokwu'),
  ('BE-otukpo','BE','Otukpo'),
  ('BE-tarka','BE','Tarka'),
  ('BE-ukum','BE','Ukum'),
  ('BE-ushongo','BE','Ushongo'),
  ('BE-vandeikya','BE','Vandeikya'),
  ('BO-abadam','BO','Abadam'),
  ('BO-askira-uba','BO','Askira/Uba'),
  ('BO-bama','BO','Bama'),
  ('BO-bayo','BO','Bayo'),
  ('BO-biu','BO','Biu'),
  ('BO-chibok','BO','Chibok'),
  ('BO-damboa','BO','Damboa'),
  ('BO-dikwa','BO','Dikwa'),
  ('BO-gubio','BO','Gubio'),
  ('BO-guzamala','BO','Guzamala'),
  ('BO-gwoza','BO','Gwoza'),
  ('BO-hawul','BO','Hawul'),
  ('BO-jere','BO','Jere'),
  ('BO-kaga','BO','Kaga'),
  ('BO-kala-balge','BO','Kala/Balge'),
  ('BO-konduga','BO','Konduga'),
  ('BO-kukawa','BO','Kukawa'),
  ('BO-kwaya-kusar','BO','Kwaya Kusar'),
  ('BO-mafa','BO','Mafa'),
  ('BO-magumeri','BO','Magumeri'),
  ('BO-maiduguri','BO','Maiduguri'),
  ('BO-marte','BO','Marte'),
  ('BO-mobbar','BO','Mobbar'),
  ('BO-monguno','BO','Monguno'),
  ('BO-ngala','BO','Ngala'),
  ('BO-nganzai','BO','Nganzai'),
  ('BO-shani','BO','Shani'),
  ('BY-brass','BY','Brass'),
  ('BY-ekeremor','BY','Ekeremor'),
  ('BY-kolokuma-opokuma','BY','Kolokuma/Opokuma'),
  ('BY-nembe','BY','Nembe'),
  ('BY-ogbia','BY','Ogbia'),
  ('BY-sagbama','BY','Sagbama'),
  ('BY-southern-ijaw','BY','Southern Ijaw'),
  ('BY-yenagoa','BY','Yenagoa'),
  ('CR-abi','CR','Abi'),
  ('CR-akamkpa','CR','Akamkpa'),
  ('CR-akpabuyo','CR','Akpabuyo'),
  ('CR-bakassi','CR','Bakassi'),
  ('CR-bekwarra','CR','Bekwarra'),
  ('CR-biase','CR','Biase'),
  ('CR-boki','CR','Boki'),
  ('CR-calabar-municipal','CR','Calabar Municipal'),
  ('CR-calabar-south','CR','Calabar South'),
  ('CR-etung','CR','Etung'),
  ('CR-ikom','CR','Ikom'),
  ('CR-obanliku','CR','Obanliku'),
  ('CR-obubra','CR','Obubra'),
  ('CR-obudu','CR','Obudu'),
  ('CR-odukpani','CR','Odukpani'),
  ('CR-ogoja','CR','Ogoja'),
  ('CR-yakurr','CR','Yakurr'),
  ('CR-yala','CR','Yala'),
  ('DE-aniocha-north','DE','Aniocha North'),
  ('DE-aniocha-south','DE','Aniocha South'),
  ('DE-bomadi','DE','Bomadi'),
  ('DE-burutu','DE','Burutu'),
  ('DE-ethiope-east','DE','Ethiope East'),
  ('DE-ethiope-west','DE','Ethiope West'),
  ('DE-ika-north-east','DE','Ika North East'),
  ('DE-ika-south','DE','Ika South'),
  ('DE-isoko-north','DE','Isoko North'),
  ('DE-isoko-south','DE','Isoko South'),
  ('DE-ndokwa-east','DE','Ndokwa East'),
  ('DE-ndokwa-west','DE','Ndokwa West'),
  ('DE-okpe','DE','Okpe'),
  ('DE-oshimili-north','DE','Oshimili North'),
  ('DE-oshimili-south','DE','Oshimili South'),
  ('DE-patani','DE','Patani'),
  ('DE-sapele','DE','Sapele'),
  ('DE-udu','DE','Udu'),
  ('DE-ughelli-north','DE','Ughelli North'),
  ('DE-ughelli-south','DE','Ughelli South'),
  ('DE-ukwuani','DE','Ukwuani'),
  ('DE-uvwie','DE','Uvwie'),
  ('DE-warri-north','DE','Warri North'),
  ('DE-warri-south','DE','Warri South'),
  ('DE-warri-south-west','DE','Warri South West'),
  ('EB-abakaliki','EB','Abakaliki'),
  ('EB-afikpo-north','EB','Afikpo North'),
  ('EB-afikpo-south','EB','Afikpo South'),
  ('EB-ebonyi','EB','Ebonyi'),
  ('EB-ezza-north','EB','Ezza North'),
  ('EB-ezza-south','EB','Ezza South'),
  ('EB-ikwo','EB','Ikwo'),
  ('EB-ishielu','EB','Ishielu'),
  ('EB-ivo','EB','Ivo'),
  ('EB-izzi','EB','Izzi'),
  ('EB-ohaozara','EB','Ohaozara'),
  ('EB-ohaukwu','EB','Ohaukwu'),
  ('EB-onicha','EB','Onicha'),
  ('ED-akoko-edo','ED','Akoko Edo'),
  ('ED-egor','ED','Egor'),
  ('ED-esan-central','ED','Esan Central'),
  ('ED-esan-north-east','ED','Esan North East'),
  ('ED-esan-south-east','ED','Esan South East'),
  ('ED-esan-west','ED','Esan West'),
  ('ED-etsako-central','ED','Etsako Central'),
  ('ED-etsako-east','ED','Etsako East'),
  ('ED-etsako-west','ED','Etsako West'),
  ('ED-igueben','ED','Igueben'),
  ('ED-ikpoba-okha','ED','Ikpoba Okha'),
  ('ED-oredo','ED','Oredo'),
  ('ED-orhionmwon','ED','Orhionmwon'),
  ('ED-ovia-north-east','ED','Ovia North East'),
  ('ED-ovia-south-west','ED','Ovia South West'),
  ('ED-owan-east','ED','Owan East'),
  ('ED-owan-west','ED','Owan West'),
  ('ED-uhunmwonde','ED','Uhunmwonde'),
  ('EK-ado-ekiti','EK','Ado-Ekiti'),
  ('EK-efon','EK','Efon'),
  ('EK-ekiti-east','EK','Ekiti East'),
  ('EK-ekiti-south-west','EK','Ekiti South West'),
  ('EK-ekiti-west','EK','Ekiti West'),
  ('EK-emure','EK','Emure'),
  ('EK-gbonyin','EK','Gbonyin'),
  ('EK-ido-osi','EK','Ido-Osi'),
  ('EK-ijero','EK','Ijero'),
  ('EK-ikere','EK','Ikere'),
  ('EK-ikole','EK','Ikole'),
  ('EK-ilejemeje','EK','Ilejemeje'),
  ('EK-irepodun-ifelodun','EK','Irepodun/Ifelodun'),
  ('EK-ise-orun','EK','Ise/Orun'),
  ('EK-moba','EK','Moba'),
  ('EK-oye','EK','Oye'),
  ('EN-aninri','EN','Aninri'),
  ('EN-awgu','EN','Awgu'),
  ('EN-enugu-east','EN','Enugu East'),
  ('EN-enugu-north','EN','Enugu North'),
  ('EN-enugu-south','EN','Enugu South'),
  ('EN-ezeagu','EN','Ezeagu'),
  ('EN-igbo-etiti','EN','Igbo Etiti'),
  ('EN-igbo-eze-north','EN','Igbo Eze North'),
  ('EN-igbo-eze-south','EN','Igbo Eze South'),
  ('EN-isi-uzo','EN','Isi-Uzo'),
  ('EN-nkanu-east','EN','Nkanu East'),
  ('EN-nkanu-west','EN','Nkanu West'),
  ('EN-nsukka','EN','Nsukka'),
  ('EN-oji-river','EN','Oji-River'),
  ('EN-udenu','EN','Udenu'),
  ('EN-udi','EN','Udi'),
  ('EN-uzo-uwani','EN','Uzo-Uwani'),
  ('FC-abaji','FC','Abaji'),
  ('FC-abuja','FC','Abuja'),
  ('FC-bwari','FC','Bwari'),
  ('FC-gwagwalada','FC','Gwagwalada'),
  ('FC-kuje','FC','Kuje'),
  ('FC-kwali','FC','Kwali'),
  ('GO-akko','GO','Akko'),
  ('GO-balanga','GO','Balanga'),
  ('GO-billiri','GO','Billiri'),
  ('GO-dukku','GO','Dukku'),
  ('GO-funakaye','GO','Funakaye'),
  ('GO-gombe','GO','Gombe'),
  ('GO-kaltungo','GO','Kaltungo'),
  ('GO-kwami','GO','Kwami'),
  ('GO-nafada','GO','Nafada'),
  ('GO-shongom','GO','Shongom'),
  ('GO-yamaltu-deba','GO','Yamaltu/Deba'),
  ('IM-aboh-mbaise','IM','Aboh Mbaise'),
  ('IM-ahiazu-mbaise','IM','Ahiazu Mbaise'),
  ('IM-ehime-mbano','IM','Ehime Mbano'),
  ('IM-ezinihitte-mbaise','IM','Ezinihitte Mbaise'),
  ('IM-ideato-north','IM','Ideato North'),
  ('IM-ideato-south','IM','Ideato South'),
  ('IM-ihitte-uboma','IM','Ihitte/Uboma'),
  ('IM-ikeduru','IM','Ikeduru'),
  ('IM-isiala-mbano','IM','Isiala Mbano'),
  ('IM-isu','IM','Isu'),
  ('IM-mbaitoli','IM','Mbaitoli'),
  ('IM-ngor-okpala','IM','Ngor Okpala'),
  ('IM-njaba','IM','Njaba'),
  ('IM-nkwerre','IM','Nkwerre'),
  ('IM-nwangele','IM','Nwangele'),
  ('IM-obowo','IM','Obowo'),
  ('IM-oguta','IM','Oguta'),
  ('IM-ohaji-egbema','IM','Ohaji/Egbema'),
  ('IM-okigwe','IM','Okigwe'),
  ('IM-onuimo','IM','Onuimo'),
  ('IM-orlu','IM','Orlu'),
  ('IM-orsu','IM','Orsu'),
  ('IM-oru-east','IM','Oru East'),
  ('IM-oru-west','IM','Oru West'),
  ('IM-owerri-municipal','IM','Owerri Municipal'),
  ('IM-owerri-north','IM','Owerri North'),
  ('IM-owerri-west','IM','Owerri West'),
  ('JI-auyo','JI','Auyo'),
  ('JI-babura','JI','Babura'),
  ('JI-biriniwa','JI','Biriniwa'),
  ('JI-birnin-kudu','JI','Birnin Kudu'),
  ('JI-buji','JI','Buji'),
  ('JI-dutse','JI','Dutse'),
  ('JI-gagarawa','JI','Gagarawa'),
  ('JI-garki','JI','Garki'),
  ('JI-gumel','JI','Gumel'),
  ('JI-guri','JI','Guri'),
  ('JI-gwaram','JI','Gwaram'),
  ('JI-gwiwa','JI','Gwiwa'),
  ('JI-hadejia','JI','Hadejia'),
  ('JI-jahun','JI','Jahun'),
  ('JI-kafin-hausa','JI','Kafin Hausa'),
  ('JI-kaugama','JI','Kaugama'),
  ('JI-kazaure','JI','Kazaure'),
  ('JI-kiri-kasama','JI','Kiri Kasama'),
  ('JI-kiyawa','JI','Kiyawa'),
  ('JI-maigatari','JI','Maigatari'),
  ('JI-malam-madori','JI','Malam Madori'),
  ('JI-miga','JI','Miga'),
  ('JI-ringim','JI','Ringim'),
  ('JI-roni','JI','Roni'),
  ('JI-sule-tankarkar','JI','Sule Tankarkar'),
  ('JI-taura','JI','Taura'),
  ('JI-yankwashi','JI','Yankwashi'),
  ('KD-birnin-gwari','KD','Birnin Gwari'),
  ('KD-chikun','KD','Chikun'),
  ('KD-giwa','KD','Giwa'),
  ('KD-igabi','KD','Igabi'),
  ('KD-ikara','KD','Ikara'),
  ('KD-jaba','KD','Jaba'),
  ('KD-jema-a','KD','Jema''a'),
  ('KD-kachia','KD','Kachia'),
  ('KD-kaduna-north','KD','Kaduna North'),
  ('KD-kaduna-south','KD','Kaduna South'),
  ('KD-kagarko','KD','Kagarko'),
  ('KD-kajuru','KD','Kajuru'),
  ('KD-kaura','KD','Kaura'),
  ('KD-kauru','KD','Kauru'),
  ('KD-kubau','KD','Kubau'),
  ('KD-kudan','KD','Kudan'),
  ('KD-lere','KD','Lere'),
  ('KD-makarfi','KD','Makarfi'),
  ('KD-sabon-gari','KD','Sabon Gari'),
  ('KD-sanga','KD','Sanga'),
  ('KD-soba','KD','Soba'),
  ('KD-zangon-kataf','KD','Zangon Kataf'),
  ('KD-zaria','KD','Zaria'),
  ('KE-aliero','KE','Aliero'),
  ('KE-arewa-dandi','KE','Arewa Dandi'),
  ('KE-argungu','KE','Argungu'),
  ('KE-augie','KE','Augie'),
  ('KE-bagudo','KE','Bagudo'),
  ('KE-birnin-kebbi','KE','Birnin Kebbi'),
  ('KE-bunza','KE','Bunza'),
  ('KE-dandi','KE','Dandi'),
  ('KE-danko-wasagu','KE','Danko-Wasagu'),
  ('KE-fakai','KE','Fakai'),
  ('KE-gwandu','KE','Gwandu'),
  ('KE-jega','KE','Jega'),
  ('KE-kalgo','KE','Kalgo'),
  ('KE-koko-besse','KE','Koko/Besse'),
  ('KE-maiyama','KE','Maiyama'),
  ('KE-ngaski','KE','Ngaski'),
  ('KE-sakaba','KE','Sakaba'),
  ('KE-shanga','KE','Shanga'),
  ('KE-suru','KE','Suru'),
  ('KE-yauri','KE','Yauri'),
  ('KE-zuru','KE','Zuru'),
  ('KN-ajingi','KN','Ajingi'),
  ('KN-albasu','KN','Albasu'),
  ('KN-bagwai','KN','Bagwai'),
  ('KN-bebeji','KN','Bebeji'),
  ('KN-bichi','KN','Bichi'),
  ('KN-bunkure','KN','Bunkure'),
  ('KN-dala','KN','Dala'),
  ('KN-dambatta','KN','Dambatta'),
  ('KN-dawakin-kudu','KN','Dawakin Kudu'),
  ('KN-dawakin-tofa','KN','Dawakin Tofa'),
  ('KN-doguwa','KN','Doguwa'),
  ('KN-fagge','KN','Fagge'),
  ('KN-gabasawa','KN','Gabasawa'),
  ('KN-garko','KN','Garko'),
  ('KN-garun-malam','KN','Garun Malam'),
  ('KN-gaya','KN','Gaya'),
  ('KN-gezawa','KN','Gezawa'),
  ('KN-gwale','KN','Gwale'),
  ('KN-gwarzo','KN','Gwarzo'),
  ('KN-kabo','KN','Kabo'),
  ('KN-kano-municipal','KN','Kano Municipal'),
  ('KN-karaye','KN','Karaye'),
  ('KN-kibiya','KN','Kibiya'),
  ('KN-kiru','KN','Kiru'),
  ('KN-kumbotso','KN','kumbotso'),
  ('KN-kunchi','KN','Kunchi'),
  ('KN-kura','KN','Kura'),
  ('KN-madobi','KN','Madobi'),
  ('KN-makoda','KN','Makoda'),
  ('KN-minjibir','KN','Minjibir'),
  ('KN-nasarawa','KN','Nasarawa'),
  ('KN-rano','KN','Rano'),
  ('KN-rimin-gado','KN','Rimin Gado'),
  ('KN-rogo','KN','Rogo'),
  ('KN-shanono','KN','Shanono'),
  ('KN-sumaila','KN','Sumaila'),
  ('KN-takai','KN','Takai'),
  ('KN-tarauni','KN','Tarauni'),
  ('KN-tofa','KN','Tofa'),
  ('KN-tsanyawa','KN','Tsanyawa'),
  ('KN-tudun-wada','KN','Tudun Wada'),
  ('KN-ungogo','KN','Ungogo'),
  ('KN-warawa','KN','Warawa'),
  ('KN-wudil','KN','Wudil'),
  ('KO-adavi','KO','Adavi'),
  ('KO-ajaokuta','KO','Ajaokuta'),
  ('KO-ankpa','KO','Ankpa'),
  ('KO-bassa','KO','Bassa'),
  ('KO-dekina','KO','Dekina'),
  ('KO-ibaji','KO','Ibaji'),
  ('KO-idah','KO','Idah'),
  ('KO-igalamela-odolu','KO','Igalamela Odolu'),
  ('KO-ijumu','KO','Ijumu'),
  ('KO-kabba-bunu','KO','Kabba/Bunu'),
  ('KO-kogi','KO','Kogi'),
  ('KO-lokoja','KO','Lokoja'),
  ('KO-mopa-muro','KO','Mopa-Muro'),
  ('KO-ofu','KO','Ofu'),
  ('KO-ogori-magongo','KO','Ogori/Magongo'),
  ('KO-okehi','KO','Okehi'),
  ('KO-okene','KO','Okene'),
  ('KO-olamaboro','KO','Olamaboro'),
  ('KO-omala','KO','Omala'),
  ('KO-yagba-east','KO','Yagba East'),
  ('KO-yagba-west','KO','Yagba West'),
  ('KT-bakori','KT','Bakori'),
  ('KT-batagarawa','KT','Batagarawa'),
  ('KT-batsari','KT','Batsari'),
  ('KT-baure','KT','Baure'),
  ('KT-bindawa','KT','Bindawa'),
  ('KT-charanchi','KT','Charanchi'),
  ('KT-dan-musa','KT','Dan Musa'),
  ('KT-dandume','KT','DanDume'),
  ('KT-danja','KT','Danja'),
  ('KT-daura','KT','Daura'),
  ('KT-dutsi','KT','Dutsi'),
  ('KT-dutsin-ma','KT','Dutsin-Ma'),
  ('KT-faskari','KT','Faskari'),
  ('KT-funtua','KT','Funtua'),
  ('KT-ingawa','KT','Ingawa'),
  ('KT-jibia','KT','Jibia'),
  ('KT-kafur','KT','Kafur'),
  ('KT-kaita','KT','Kaita'),
  ('KT-kankara','KT','Kankara'),
  ('KT-kankia','KT','Kankia'),
  ('KT-katsina','KT','Katsina'),
  ('KT-kurfi','KT','Kurfi'),
  ('KT-kusada','KT','Kusada'),
  ('KT-mai-adua','KT','Mai''Adua'),
  ('KT-malumfashi','KT','Malumfashi'),
  ('KT-mani','KT','Mani'),
  ('KT-mashi','KT','Mashi'),
  ('KT-matazu','KT','Matazu'),
  ('KT-musawa','KT','Musawa'),
  ('KT-rimi','KT','Rimi'),
  ('KT-sabuwa','KT','Sabuwa'),
  ('KT-safana','KT','Safana'),
  ('KT-sandamu','KT','Sandamu'),
  ('KT-zango','KT','Zango'),
  ('KW-asa','KW','Asa'),
  ('KW-baruten','KW','Baruten'),
  ('KW-edu','KW','Edu'),
  ('KW-ekiti','KW','Ekiti'),
  ('KW-ifelodun','KW','Ifelodun'),
  ('KW-ilorin-east','KW','Ilorin East'),
  ('KW-ilorin-south','KW','Ilorin South'),
  ('KW-ilorin-west','KW','Ilorin West'),
  ('KW-irepodun','KW','Irepodun'),
  ('KW-isin','KW','Isin'),
  ('KW-kaiama','KW','Kaiama'),
  ('KW-moro','KW','Moro'),
  ('KW-offa','KW','Offa'),
  ('KW-oke-ero','KW','Oke-Ero'),
  ('KW-oyun','KW','Oyun'),
  ('KW-pategi','KW','Pategi'),
  ('LA-agege','LA','Agege'),
  ('LA-ajeromi-ifelodun','LA','Ajeromi-Ifelodun'),
  ('LA-alimosho','LA','Alimosho'),
  ('LA-amuwo-odofin','LA','Amuwo-Odofin'),
  ('LA-apapa','LA','Apapa'),
  ('LA-badagry','LA','Badagry'),
  ('LA-epe','LA','Epe'),
  ('LA-eti-osa','LA','Eti-Osa'),
  ('LA-ibeju-lekki','LA','Ibeju-Lekki'),
  ('LA-ifako-ijaiye','LA','Ifako-Ijaiye'),
  ('LA-ikeja','LA','Ikeja'),
  ('LA-ikorodu','LA','Ikorodu'),
  ('LA-kosofe','LA','Kosofe'),
  ('LA-lagos-island','LA','Lagos Island'),
  ('LA-lagos-mainland','LA','Lagos Mainland'),
  ('LA-mushin','LA','Mushin'),
  ('LA-ojo','LA','Ojo'),
  ('LA-oshodi-isolo','LA','Oshodi-Isolo'),
  ('LA-somolu','LA','Somolu'),
  ('LA-surulere','LA','Surulere'),
  ('NA-akwanga','NA','Akwanga'),
  ('NA-awe','NA','Awe'),
  ('NA-doma','NA','Doma'),
  ('NA-karu','NA','Karu'),
  ('NA-keana','NA','Keana'),
  ('NA-keffi','NA','Keffi'),
  ('NA-kokona','NA','Kokona'),
  ('NA-lafia','NA','Lafia'),
  ('NA-nasarawa','NA','Nasarawa'),
  ('NA-nasarawa-egon','NA','Nasarawa Egon'),
  ('NA-obi','NA','Obi'),
  ('NA-toto','NA','Toto'),
  ('NA-wamba','NA','Wamba'),
  ('NI-agaie','NI','Agaie'),
  ('NI-agwara','NI','Agwara'),
  ('NI-bida','NI','Bida'),
  ('NI-borgu','NI','Borgu'),
  ('NI-bosso','NI','Bosso'),
  ('NI-chanchaga','NI','Chanchaga'),
  ('NI-edati','NI','Edati'),
  ('NI-gbako','NI','Gbako'),
  ('NI-gurara','NI','Gurara'),
  ('NI-katcha','NI','Katcha'),
  ('NI-kontagora','NI','Kontagora'),
  ('NI-lapai','NI','Lapai'),
  ('NI-lavun','NI','Lavun'),
  ('NI-magama','NI','Magama'),
  ('NI-mariga','NI','Mariga'),
  ('NI-mashegu','NI','Mashegu'),
  ('NI-mokwa','NI','Mokwa'),
  ('NI-munya','NI','Munya'),
  ('NI-paikoro','NI','Paikoro'),
  ('NI-rafi','NI','Rafi'),
  ('NI-rijau','NI','Rijau'),
  ('NI-shiroro','NI','Shiroro'),
  ('NI-suleja','NI','Suleja'),
  ('NI-tafa','NI','Tafa'),
  ('NI-wushishi','NI','Wushishi'),
  ('OG-abeokuta-north','OG','Abeokuta North'),
  ('OG-abeokuta-south','OG','Abeokuta South'),
  ('OG-ado-odo-ota','OG','Ado-Odo/Ota'),
  ('OG-ewekoro','OG','Ewekoro'),
  ('OG-ifo','OG','Ifo'),
  ('OG-ijebu-east','OG','Ijebu East'),
  ('OG-ijebu-north','OG','Ijebu North'),
  ('OG-ijebu-north-east','OG','Ijebu North East'),
  ('OG-ijebu-ode','OG','Ijebu Ode'),
  ('OG-ikenne','OG','Ikenne'),
  ('OG-imeko-afon','OG','Imeko Afon'),
  ('OG-ipokia','OG','Ipokia'),
  ('OG-obafemi-owode','OG','Obafemi Owode'),
  ('OG-odeda','OG','Odeda'),
  ('OG-odogbolu','OG','Odogbolu'),
  ('OG-ogun-waterside','OG','Ogun Waterside'),
  ('OG-remo-north','OG','Remo North'),
  ('OG-shagamu','OG','Shagamu'),
  ('OG-yewa-north','OG','Yewa North'),
  ('OG-yewa-south','OG','Yewa South'),
  ('ON-akoko-north-east','ON','Akoko North East'),
  ('ON-akoko-north-west','ON','Akoko North West'),
  ('ON-akoko-south-east','ON','Akoko South East'),
  ('ON-akoko-south-west','ON','Akoko South West'),
  ('ON-akure-north','ON','Akure North'),
  ('ON-akure-south','ON','Akure South'),
  ('ON-ese-odo','ON','Ese Odo'),
  ('ON-idanre','ON','Idanre'),
  ('ON-ifedore','ON','Ifedore'),
  ('ON-ilaje','ON','Ilaje'),
  ('ON-ile-oluji-okeigbo','ON','Ile Oluji/Okeigbo'),
  ('ON-irele','ON','Irele'),
  ('ON-odigbo','ON','Odigbo'),
  ('ON-okitipupa','ON','Okitipupa'),
  ('ON-ondo-east','ON','Ondo East'),
  ('ON-ondo-west','ON','Ondo West'),
  ('ON-ose','ON','Ose'),
  ('ON-owo','ON','Owo'),
  ('OS-aiyedire','OS','Aiyedire'),
  ('OS-atakunmosa-east','OS','Atakunmosa East'),
  ('OS-atakunmosa-west','OS','Atakunmosa West'),
  ('OS-ayedaade','OS','Ayedaade'),
  ('OS-boluwaduro','OS','Boluwaduro'),
  ('OS-boripe','OS','Boripe'),
  ('OS-ede-north','OS','Ede North'),
  ('OS-ede-south','OS','Ede South'),
  ('OS-egbedore','OS','Egbedore'),
  ('OS-ejigbo','OS','Ejigbo'),
  ('OS-ife-central','OS','Ife Central'),
  ('OS-ife-east','OS','Ife East'),
  ('OS-ife-north','OS','Ife North'),
  ('OS-ife-south','OS','Ife South'),
  ('OS-ifedayo','OS','Ifedayo'),
  ('OS-ifelodun','OS','Ifelodun'),
  ('OS-ila','OS','Ila'),
  ('OS-ilesa-east','OS','Ilesa East'),
  ('OS-ilesa-west','OS','Ilesa West'),
  ('OS-irepodun','OS','Irepodun'),
  ('OS-irewole','OS','Irewole'),
  ('OS-isokan','OS','Isokan'),
  ('OS-iwo','OS','Iwo'),
  ('OS-obokun','OS','Obokun'),
  ('OS-odo-otin','OS','Odo-Otin'),
  ('OS-ola-oluwa','OS','Ola-Oluwa'),
  ('OS-olorunda','OS','Olorunda'),
  ('OS-oriade','OS','Oriade'),
  ('OS-orolu','OS','Orolu'),
  ('OS-osogbo','OS','Osogbo'),
  ('OY-afijio','OY','Afijio'),
  ('OY-akinyele','OY','Akinyele'),
  ('OY-atiba','OY','Atiba'),
  ('OY-atisbo','OY','Atisbo'),
  ('OY-egbeda','OY','Egbeda'),
  ('OY-ibadan-north','OY','Ibadan North'),
  ('OY-ibadan-north-east','OY','Ibadan North East'),
  ('OY-ibadan-north-west','OY','Ibadan North West'),
  ('OY-ibadan-south-east','OY','Ibadan South East'),
  ('OY-ibadan-south-west','OY','Ibadan South West'),
  ('OY-ibarapa-central','OY','Ibarapa Central'),
  ('OY-ibarapa-east','OY','Ibarapa East'),
  ('OY-ibarapa-north','OY','Ibarapa North'),
  ('OY-ido','OY','Ido'),
  ('OY-irepo','OY','Irepo'),
  ('OY-iseyin','OY','Iseyin'),
  ('OY-itesiwaju','OY','Itesiwaju'),
  ('OY-iwajowa','OY','Iwajowa'),
  ('OY-kajola','OY','Kajola'),
  ('OY-lagelu','OY','Lagelu'),
  ('OY-ogbomosho-north','OY','Ogbomosho North'),
  ('OY-ogbomosho-south','OY','Ogbomosho South'),
  ('OY-ogo-oluwa','OY','Ogo Oluwa'),
  ('OY-olorunsogo','OY','Olorunsogo'),
  ('OY-oluyole','OY','Oluyole'),
  ('OY-ona-ara','OY','Ona Ara'),
  ('OY-oorelope','OY','Oorelope'),
  ('OY-ori-ire','OY','Ori Ire'),
  ('OY-oyo-east','OY','Oyo East'),
  ('OY-oyo-west','OY','Oyo West'),
  ('OY-saki-east','OY','Saki East'),
  ('OY-saki-west','OY','Saki West'),
  ('OY-surulere','OY','Surulere'),
  ('PL-barkin-ladi','PL','Barkin Ladi'),
  ('PL-bassa','PL','Bassa'),
  ('PL-bokkos','PL','Bokkos'),
  ('PL-jos-east','PL','Jos East'),
  ('PL-jos-north','PL','Jos North'),
  ('PL-jos-south','PL','Jos South'),
  ('PL-kanam','PL','Kanam'),
  ('PL-kanke','PL','Kanke'),
  ('PL-langtang-north','PL','Langtang North'),
  ('PL-langtang-south','PL','Langtang South'),
  ('PL-mangu','PL','Mangu'),
  ('PL-mikang','PL','Mikang'),
  ('PL-pankshin','PL','Pankshin'),
  ('PL-qua-an-pan','PL','Qua''an Pan'),
  ('PL-riyom','PL','Riyom'),
  ('PL-shendam','PL','Shendam'),
  ('PL-wase','PL','Wase'),
  ('RI-abua-odual','RI','Abua-Odual'),
  ('RI-ahoada-east','RI','Ahoada East'),
  ('RI-ahoada-west','RI','Ahoada West'),
  ('RI-akuku-toru','RI','Akuku-Toru'),
  ('RI-andoni','RI','Andoni'),
  ('RI-asari-toru','RI','Asari-Toru'),
  ('RI-bonny','RI','Bonny'),
  ('RI-degema','RI','Degema'),
  ('RI-eleme','RI','Eleme'),
  ('RI-emohua','RI','Emohua'),
  ('RI-etche','RI','Etche'),
  ('RI-gokana','RI','Gokana'),
  ('RI-ikwerre','RI','Ikwerre'),
  ('RI-khana','RI','Khana'),
  ('RI-obio-akpor','RI','Obio/Akpor'),
  ('RI-ogba-egbema-ndoni','RI','Ogba/Egbema/Ndoni'),
  ('RI-ogu-bolo','RI','Ogu/Bolo'),
  ('RI-okrika','RI','Okrika'),
  ('RI-omuma','RI','Omuma'),
  ('RI-opobo-nkoro','RI','Opobo/Nkoro'),
  ('RI-oyigbo','RI','Oyigbo'),
  ('RI-port-harcourt','RI','Port Harcourt'),
  ('RI-tai','RI','Tai'),
  ('SO-binji','SO','Binji'),
  ('SO-bodinga','SO','Bodinga'),
  ('SO-dange-shuni','SO','Dange/Shuni'),
  ('SO-gada','SO','Gada'),
  ('SO-goronyo','SO','Goronyo'),
  ('SO-gudu','SO','Gudu'),
  ('SO-gwadabawa','SO','Gwadabawa'),
  ('SO-illela','SO','Illela'),
  ('SO-isa','SO','Isa'),
  ('SO-kebbe','SO','Kebbe'),
  ('SO-kware','SO','Kware'),
  ('SO-rabah','SO','Rabah'),
  ('SO-sabon-birni','SO','Sabon Birni'),
  ('SO-shagari','SO','Shagari'),
  ('SO-silame','SO','Silame'),
  ('SO-sokoto-north','SO','Sokoto North'),
  ('SO-sokoto-south','SO','Sokoto South'),
  ('SO-tambuwal','SO','Tambuwal'),
  ('SO-tangaza','SO','Tangaza'),
  ('SO-tureta','SO','Tureta'),
  ('SO-wamako','SO','Wamako'),
  ('SO-wurno','SO','Wurno'),
  ('SO-yabo','SO','Yabo'),
  ('TA-ardo-kola','TA','Ardo Kola'),
  ('TA-bali','TA','Bali'),
  ('TA-donga','TA','Donga'),
  ('TA-gashaka','TA','Gashaka'),
  ('TA-gassol','TA','Gassol'),
  ('TA-ibi','TA','Ibi'),
  ('TA-jalingo','TA','Jalingo'),
  ('TA-karim-lamido','TA','Karim Lamido'),
  ('TA-kurmi','TA','Kurmi'),
  ('TA-lau','TA','Lau'),
  ('TA-sardauna','TA','Sardauna'),
  ('TA-takum','TA','Takum'),
  ('TA-ussa','TA','Ussa'),
  ('TA-wukari','TA','Wukari'),
  ('TA-yorro','TA','Yorro'),
  ('TA-zing','TA','Zing'),
  ('YO-bade','YO','Bade'),
  ('YO-bursari','YO','Bursari'),
  ('YO-damaturu','YO','Damaturu'),
  ('YO-fika','YO','Fika'),
  ('YO-fune','YO','Fune'),
  ('YO-geidam','YO','Geidam'),
  ('YO-gujba','YO','Gujba'),
  ('YO-gulani','YO','Gulani'),
  ('YO-jakusko','YO','Jakusko'),
  ('YO-karasuwa','YO','Karasuwa'),
  ('YO-machina','YO','Machina'),
  ('YO-nangere','YO','Nangere'),
  ('YO-nguru','YO','Nguru'),
  ('YO-potiskum','YO','Potiskum'),
  ('YO-tarmuwa','YO','Tarmuwa'),
  ('YO-yunusari','YO','Yunusari'),
  ('YO-yusufari','YO','Yusufari'),
  ('ZA-anka','ZA','Anka'),
  ('ZA-bakura','ZA','Bakura'),
  ('ZA-birnin-magaji-kiyaw','ZA','Birnin Magaji/Kiyaw'),
  ('ZA-bukkuyum','ZA','Bukkuyum'),
  ('ZA-bungudu','ZA','Bungudu'),
  ('ZA-gummi','ZA','Gummi'),
  ('ZA-gusau','ZA','Gusau'),
  ('ZA-kaura-namoda','ZA','Kaura Namoda'),
  ('ZA-maradun','ZA','Maradun'),
  ('ZA-maru','ZA','Maru'),
  ('ZA-shinkafi','ZA','Shinkafi'),
  ('ZA-talata-mafara','ZA','Talata Mafara'),
  ('ZA-tsafe','ZA','Tsafe'),
  ('ZA-zurmi','ZA','Zurmi')
on conflict (code) do nothing;

-- A truncated dataset must fail loudly rather than silently degrade the feed.
do $$
declare n integer;
begin
  select count(*) into n from public.ng_lgas;
  if n <> 774 then
    raise exception 'expected 774 LGAs, found %', n;
  end if;
end $$;
